force-app/main/default/objects/TREX1__Booking__c/TREX1__Booking__c.object-meta.xml
<CustomObject>
    <description>Represents every time based booking in the system.</description>
    <label>Booking</label>
    <nameField>
        <displayFormat>BN-{00000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TREX1__Booking__c/fields/Booking_Rate_Calculation_Mode__c.field-meta.xml
<CustomField>
    <fullName>Booking_Rate_Calculation_Mode__c</fullName>
    <defaultValue>&apos;Automatic&apos;</defaultValue>
    <description>If set to Automatic, rates and details will be automatically generated from Booking and Rental Rate information. Set to manual to override these values.</description>
    <inlineHelpText>If set to Automatic, rates and details will be automatically generated from Booking and Rental Rate information. Set to manual to override these values.</inlineHelpText>
    <label>Booking Rate Calculation Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TREX1__Booking__c/fields/TREX1__book_Function__c.field-meta.xml
<CustomField>
    <fullName>TREX1__book_Function__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This holds the ID of the function associated to this booking. Used in all automation. Set automatically if you populate the &apos;Set Function&apos; field.</description>
    <inlineHelpText>This holds the ID of the function associated to this booking. Used in all automation. Set automatically if you populate the &apos;Set Function&apos; field.</inlineHelpText>
    <label>Function</label>
    <referenceTo>TREX1__Function__c</referenceTo>
    <relationshipLabel>Function Bookings</relationshipLabel>
    <relationshipName>Function_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TREX1__Booking__c/fields/TREX1__End_Time__c.field-meta.xml
<CustomField>
    <fullName>TREX1__End_Time__c</fullName>
    <description>The ending date and time of the booking.</description>
    <inlineHelpText>The ending date and time of the booking.</inlineHelpText>
    <label>End Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TREX1__Booking__c/fields/TREX1__Event_Name__c.field-meta.xml
<CustomField>
    <fullName>TREX1__Event_Name__c</fullName>
    <description>Name the venue</description>
    <inlineHelpText>Name the venue</inlineHelpText>
    <label>Event Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TREX1__Booking__c/fields/TREX1__Facility__c.field-meta.xml
<CustomField>
    <fullName>TREX1__Facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The facility this booking is for, if applicable.</description>
    <inlineHelpText>The facility this booking is for, if applicable.</inlineHelpText>
    <label>Facility</label>
    <referenceTo>TREX1__Facility__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TREX1__Booking__c/fields/TREX1__Function_ID__c.field-meta.xml
<CustomField>
    <fullName>TREX1__Function_ID__c</fullName>
    <description>This holds the ID of the function associated to this booking. Used in all automation. Set automatically if you populate the &apos;Set Function&apos; field. This is used over the lookup to avoid record skew issues.</description>
    <externalId>true</externalId>
    <inlineHelpText>This holds the ID of the function associated to this booking. Used in all automation. Set automatically if you populate the &apos;Set Function&apos; field. This is used over the lookup to avoid record skew issues.</inlineHelpText>
    <label>Function Text ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TREX1__Booking__c/fields/TREX1__Function_Name__c.field-meta.xml
<CustomField>
    <fullName>TREX1__Function_Name__c</fullName>
    <description>The name of the function of this booking. Populated automatically by the Set Function field. Do not attempt to overwrite.</description>
    <inlineHelpText>The name of the function of this booking. Populated automatically by the Set Function field. Do not attempt to overwrite.</inlineHelpText>
    <label>Current Function</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TREX1__Booking__c/fields/TREX1__Setup_Time_Required__c.field-meta.xml
<CustomField>
    <fullName>TREX1__Setup_Time_Required__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Time required to setup in minutes.</description>
    <inlineHelpText>Time required to setup in minutes.</inlineHelpText>
    <label>Setup Time Required</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TREX1__Booking__c/fields/TREX1__Start_Time__c.field-meta.xml
<CustomField>
    <fullName>TREX1__Start_Time__c</fullName>
    <description>The start date and time of this booking.</description>
    <inlineHelpText>The start date and time of this booking.</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TREX1__Booking__c/fields/TREX1__Status__c.field-meta.xml
<CustomField>
    <fullName>TREX1__Status__c</fullName>
    <description>The status of this booking. These values are hardcoded in the system to different functionality, do not change.</description>
    <inlineHelpText>The status of this booking. These values are hardcoded in the system to different functionality, do not change.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Firmed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TREX1__Booking__c/fields/TREX1__Tear_Down_Time_Required__c.field-meta.xml
<CustomField>
    <fullName>TREX1__Tear_Down_Time_Required__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Tear down time required in minutes.</description>
    <inlineHelpText>Tear down time required in minutes.</inlineHelpText>
    <label>Tear Down Time Required</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TREX1__Booking__c/fields/TREX1__Type__c.field-meta.xml
<CustomField>
    <fullName>TREX1__Type__c</fullName>
    <description>Type of booking</description>
    <inlineHelpText>Type of booking</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Administrative</fullName>
            </value>
            <value>
                <fullName>Rental</fullName>
            </value>
            <value>
                <fullName>Program</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Course</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PublicCalendarController_Test.cls
@IsTest
private class PublicCalendarController_Test {

    private static Id facilityBookingRTId = Schema.SObjectType.TREX1__Booking__c.getRecordTypeInfosByDeveloperName().get('Facility').getRecordTypeId();
    private static final String ADMIN_BOOKING_TYPE = 'Administrative';
    private static final String BOOKING_EVENT_NAME = 'Test Rental';
    private static final String BOOKING_STATUS = 'Draft';
    private static final String CALCULATION_MODE_AUTOMATIC = 'Automatic';

    @TestSetup
    static void makeData() {
        TREX1__Function__c function = TestDataFactory.createFunctions(1).get(0);
        insert function;

        TREX1__Location__c location = TestDataFactory.createLocations(1).get(0);
        insert location;

        TREX1__Facility__c facility = TestDataFactory.createFacilities(1).get(0);
        facility.TREX1__Location__c = location.Id;
        insert facility;

        List<TREX1__Booking_Contract_Option__c> lstBCOs = TestDataFactory.createBookingContractOptions(
            new List<TREX1__Facility__c>{ facility },
            new List<TREX1__Function__c>{ function }
        );
        insert lstBCOs;

        List<TREX1__Booking__c> lstBookings = new List<TREX1__Booking__c>();
        for (Integer i = 0; i < 10; i++) {
            lstBookings.add(
                new TREX1__Booking__c(
                    RecordTypeId = facilityBookingRTId,
                    TREX1__Facility__c = facility.Id,
                    TREX1__Function_ID__c = function.Id,
                    TREX1__Function_Name__c = function.Name,
                    TREX1__book_Function__c = function.Id,
                    TREX1__Type__c = ADMIN_BOOKING_TYPE,
                    TREX1__Status__c = BOOKING_STATUS,
                    TREX1__Start_Time__c = Datetime.newInstance(Date.today() + i, Time.newInstance(7, 0, 0, 0)),
                    TREX1__End_Time__c = Datetime.newInstance(Date.today() + i, Time.newInstance(8, 0, 0, 0)),
                    TREX1__Event_Name__c = BOOKING_EVENT_NAME,
                    TREX1__Setup_Time_Required__c = 0,
                    TREX1__Tear_Down_Time_Required__c = 0,
                    Booking_Rate_Calculation_Mode__c = CALCULATION_MODE_AUTOMATIC
                )
            );
        }
        insert lstBookings;
    }
    
    @IsTest
    static void testGetPublicBookings() {
        TREX1__Function__c function = [SELECT Name FROM TREX1__Function__c LIMIT 1];

        List<PublicCalendarController.Booking> lstEvents;
        Test.startTest();
        lstEvents = PublicCalendarController.getPublicBookings(function.Name);
        Test.stopTest();

        Assert.areEqual(
            function.Name, 
            lstEvents[0].functionName, 
            'Should not receive events with a different function name'
        );

        List<TREX1__Booking__c> lstBookings = [
            SELECT Id 
              FROM TREX1__Booking__c 
             WHERE TREX1__Function_Name__c = :function.Name
               AND TREX1__Start_Time__c >= TODAY
        ];

        Assert.areEqual(
            lstBookings.size(), 
            lstEvents.size(), 
            'Should have received a data wrapper object for each upcoming booking of the function type'
        );
    }
    
}